
import React from 'react';
import {
  LayoutDashboard,
  FileText,
  Users,
  FileStack,
  BarChart3,
  Settings,
  Bell,
  Search,
  ChevronDown,
  TrendingUp,
  TrendingDown,
  DollarSign,
  PieChart,
  Calendar,
  AlertTriangle,
  Plus,
  Filter,
  Save,
  Download,
  Trash2,
  Edit,
  X,
  Eye,
  MoreHorizontal,
  Layers,
  ShieldCheck,
  User,
  Lock,
  ArrowRight,
  LogOut,
  Building2,
  Tag,
  Briefcase,
  CheckCircle2,
  List,
  MapPin,
  Phone,
  UploadCloud,
  Paperclip,
  File,
  Truck,
  ChevronLeft,
  ChevronRight,
  ChevronsLeft,
  ChevronsRight,
  FileSpreadsheet,
  Hash,
  Mail
} from 'lucide-react';

export const Icons = {
  Dashboard: LayoutDashboard,
  Contract: FileText,
  Customer: Users,
  Document: FileStack,
  Report: BarChart3,
  Settings: Settings,
  Bell: Bell,
  Search: Search,
  ChevronDown: ChevronDown,
  TrendingUp: TrendingUp,
  TrendingDown: TrendingDown,
  Dollar: DollarSign,
  Chart: PieChart,
  Calendar: Calendar,
  Warning: AlertTriangle,
  Plus: Plus,
  Filter: Filter,
  Save: Save,
  Download: Download,
  Trash: Trash2,
  Edit: Edit,
  X: X,
  Eye: Eye,
  More: MoreHorizontal,
  Category: Layers,
  Admin: ShieldCheck,
  ShieldCheck: ShieldCheck, // Added to match keys used in Admin Menu
  User: User,
  Lock: Lock,
  ArrowRight: ArrowRight,
  LogOut: LogOut,
  Building: Building2,
  Tag: Tag,
  Briefcase: Briefcase,
  Check: CheckCircle2,
  List: List,
  MapPin: MapPin,
  Phone: Phone,
  Users: Users,
  Upload: UploadCloud,
  Attach: Paperclip,
  File: File,
  FileText: FileText,
  Supplier: Truck,
  ChevronLeft: ChevronLeft,
  ChevronRight: ChevronRight,
  ChevronsLeft: ChevronsLeft,
  ChevronsRight: ChevronsRight,
  Csv: File,
  Excel: FileSpreadsheet,
  Hash: Hash,
  Mail: Mail,
};
